spring:
  profiles: dev
  profiles.include:
    - 'message_codes'
    - 'commons'
    - 'mailer'

livy:
  url: http://192.168.10.170:8998/batches
  numExecutors: 1 # 10
  file: s3://near-places/tmp/kapil/scripts/main.py
  executorCores: 2 #  5
  executorMemory: 1g #  6
  driverMemory: 1g #  6
  #url: http://192.168.11.68:8998/batches
  #historicJobLocation: hdfs://wdc-prod-hadoop-nn.adnear.net:8020/user/dataengg/deploy/historic_segment_collection.py

mongo:
  uriInConsul: "template.mongo.uri"
  database: "near_db"

redis:
  url: "localhost"

---

spring:
  profiles: staging
  profiles.include:
    - 'message_codes'
    - 'commons'

livy:
  host: http://wdc04-prod-thor-compserv02.adnear.net:8998
  createBatchEndpoint: /batches
  #historicJobLocation: hdfs://wdc-prod-hadoop-nn.adnear.net:8020/user/dataengg/deploy/historic_segment_collection.py

mongo:
    uriInConsul: "dev.allspark.mongo.uri"
    database: "test"

---

spring:
  profiles: prod
  profiles.include:
    - 'message_codes'
    - 'commons'

livy:
  host: http://wdc04-prod-thor-compserv02.adnear.net:8998
  createBatchEndpoint: /batches
  #historicJobLocation: hdfs://wdc-prod-hadoop-nn.adnear.net:8020/user/dataengg/deploy/historic_segment_collection.py

mongo:
  uriInConsul: "dev.allspark.mongo.uri"
  database: "test"